version: '3.8'

services:
  db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=D1q9f0C2&PEW
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
  app:
    driver: local
